[project]
name = "hexlet-code"
version = "0.1.0"
description = "Project task manager"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.0.1",
    "django>=6.0",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.2.1",
]
